### ISSUE TITLE
Add Unix tools for better terminal experience

### ISSUE THREAD

**Issue by pierrepo** [CVandiedonck/geno_bioinfo_r#1]
Tools such as nano, tree... could be very useful in the terminal.

For this, we need to create the file `binder/apt.txt` with content:
```
vim
nano
gawk
tree
htop
```

**Comment by CVandiedonck** [comment]
I agree!

**Comment by pierrepo** [comment]
This issue is more important than expected. Students cannot auto-merge branches without console editors (`vim`, `nano`...)

**Comment by CVandiedonck** [comment]
Really? I hope it was present in the genomics-bioinformatics option environment.

**Comment by pierrepo** [comment]
Unfortunately, yes.

**Comment by CVandiedonck** [comment]
You mean no? Did you generate a new environment for them?

**Comment by pierrepo** [comment]
@CVandiedonck can you please add me as a collaborator on this repo?

**Comment by CVandiedonck** [comment]
done
